[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61", "wheel"]

[project]
name = "invenio-modular-detail-page"
version = "0.3.1-dev1"
description = "InvenioRDM extension that adds a modular record detail page"
readme = "README.md"
keywords = ["invenio", "modular", "ui"]
license = { file = "LICENSE" }
authors = [{ name = "MESH Research", email = "scottia4@msu.edu" }]
requires-python = ">=3.12"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = ["invenio-app-rdm<14"]

optional-dependencies.dev = [
  "bumpver",
  "check-manifest",
  "ipykernel",
  "pip-tools",
]
optional-dependencies.test = [
  "coverage",
  "docker-services-cli",
  "pytest-black",
  "pytest-invenio>=3.3,<4",
  "selenium",
  "sphinx>=4.5",
]
urls.Homepage = "https://github.com/MESH-Research/invenio-modular-detail-page"
entry-points."invenio_assets.webpack".invenio_modular_detail_page_theme = "invenio_modular_detail_page.webpack:theme"
entry-points."invenio_base.apps".invenio_modular_detail_page = "invenio_modular_detail_page:InvenioModularDetailPage"
entry-points."invenio_base.blueprints".invenio_modular_detail_page = "invenio_modular_detail_page.ext:create_blueprint"
entry-points."invenio_i18n.translations".messages = "invenio_modular_detail_page"

[tool.check-manifest]
ignore = [
  "PKG-INFO",
  ".egg-info",
  ".egg-info/*",
  "setup.cfg",
  ".DS_Store",
  ".hgtags",
  ".hgsigs",
  ".hgignore",
  ".gitignore",
  ".bzrignore",
  ".gitattributes",
  ".github/*",
  ".travis.yml",
  "Jenkinsfile",
  "* .mo",
  "dist/*",
  "build/*",
  "invenio_modular_detail_page/dependencies/*",
]

[tool.pytest.ini_options]
addopts = "--black --isort --pydocstyle --doctest-glob=\"*.rst\" --doctest-modules --cov=invenio_modular_detail_page --cov-report=term-missing"
testpaths = ["docs", "tests", "invenio_modular_detail_page"]

[tool.pydocstyle]
add-ignore = ["D401"]

[tool.sphinx]
source-dir = "docs/"
build-dir = "docs/_build"
all_files = true

[tool.babel.compile_catalog]
directory = "invenio_modular_detail_page/translations/"
use-fuzzy = true

[tool.babel.extract_messages]
copyright_holder = "MESH Research"
msgid_bugs_address = "scottia4@msu.edu"
mapping-file = "babel.ini"
output-file = "invenio_modular_detail_page/translations/messages.pot"
add-comments = "NOTE"

[tool.babel.init_catalog]
input-file = "invenio_modular_detail_page/translations/messages.pot"
output-dir = "invenio_modular_detail_page/translations/"

[tool.babel.update_catalog]
input-file = "invenio_modular_detail_page/translations/messages.pot"
output-dir = "invenio_modular_detail_page/translations/"

[tool.bumpver]
current_version = "0.3.1-dev1"
version_pattern = "MAJOR.MINOR.PATCH[-TAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = false
tag = false
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['^version = "{version}"', '^current_version = "{version}"']
"README.md" = ['^Version {version}']
"VERSION" = ['^"{version}"']
"invenio_modular_detail_page/__init__.py" = ['^__version__ = "{version}"']
